spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/project_lib
    password:
    username: harmonic
  jpa:
    hibernate:
      ddl-auto: none